### ISSUE TITLE
Update npm release

### ISSUE THREAD

**Issue by codeback** [larafale/mangopay#36]
Please, update npm

**Comment by larafale** [comment]
https://github.com/larafale/mangopay/releases/tag/0.0.9

**Comment by codeback** [comment]
Please, update npm again

**Comment by larafale** [comment]
@codeback do you want npm access ? give me your username

**Comment by codeback** [comment]
It's codeback, the same as the github user. 

Thanks!

**Comment by larafale** [comment]
ok you are in !
