### ISSUE TITLE
Authorization error while creating new user

### ISSUE THREAD

**Issue by andriy-polanski** [larafale/mangopay#47]
Hi. I'm trying to create new user using user rest API.

With following configuration

{
username: 'bundle',
password: '{my password used when I login to dashboard}',
production: false
}

But I'm getting following error.

https://www.dropbox.com/s/gjk0l6n6g3glrys/mangopay.PNG?dl=0

What is the reason?

**Comment by larafale** [comment]
the password should be your private key, and not your account password. that's why you are getting an unauthorized access.

**Comment by andriy-polanski** [comment]
@larafale Thanks for your message.

By the way, where can I find my private key?

https://www.dropbox.com/s/i9fafrd4y8fq5ry/mangopay1.PNG?dl=0

**Comment by larafale** [comment]
To be honest i never really used their API as i'm not affiliated with Mangopay at all :)
They call it the passphrase, and i think you get one right after your registration.
It should be available in your dashboard ( i don't know where ), but if not, try to ask their support team.

sorry :)
