### ISSUE TITLE
Update to 2.01

### ISSUE THREAD

**Issue by tcastelli** [larafale/mangopay#49]
There are some slight changes for addresses in 2.01
https://docs.mangopay.com/api-v2-01-overview/
Any chance of implementing those updates?

**Comment by PedroEsperanca** [comment]
+1

**Comment by larafale** [comment]
guys you should send a PR because i don't have time anytime soon :(

**Comment by PedroEsperanca** [comment]
https://github.com/larafale/mangopay/pull/52 hope this covers it

please accept my pull requests and bump the version ;)

**Comment by tcastelli** [comment]
i think at least this line should be changed too (or at least become configurable if we don't want to use v2)
````javascript
this._api = {
    auth: false,
    protocol: 'https',
    host: 'api.sandbox.mangopay.com',
    port: '',
    basePath: '/v2/' + this._options.username,
    timeout: 120 * 1000
  }
````
As stated on the website, default call should be made to
     Example request for POST https://www.mangopay.com/v2.01/YourClientId/users/natural/ (JSON)
Although I think there's a typo and it should be api.mangopay.com/v2.01 not mangopay.com

**Comment by larafale** [comment]
in 0.0.15 0dec2f1cfde0840b9f643462bd903abcfdc460ee you can now specify an api version in `options`

default is `v2`

```
Mango({
    username: Creds.username
  , password: Creds.password
  , version: 'v2.01'
})
```
