### ISSUE TITLE
Birthday 0 leads to error

### ISSUE THREAD

**Issue by mstn** [larafale/mangopay#54]
0 is the unix time for 01/01/1970. Hence, it is a legitimate value. However, when a user is created with birthday field set to 0, this error is raised:

     Error: parameter "Birthday" is required

The reason is obviously here
https://github.com/larafale/mangopay/blob/master/lib/httpMethod.js#L34

**Comment by fix** [comment]
put unix time + 1 millis to each date....

**Comment by mstn** [comment]
It is what I did. But it is a hack. Imo the lib should handle this case. However, I understand it is a lesser issue.

**Comment by godspeedelbow** [comment]
Yeah, this is an easy fix. The first one who files a PR gets five karma points

**Comment by godspeedelbow** [comment]
fixed in 0.2.1 (but not yet in NPM)
