### ISSUE TITLE
Error when a parameter required by a method is missing

### ISSUE THREAD

**Issue by Dollab** [larafale/mangopay#57]
Hi, first of all thanks for this great module.
I've noticed that when a parameter required by a method is missing (e.g. an address when registering a bank account) the middleware directly throws an error which crashes the app. (httpMethod.js l.34 and l.38)
Wouldn't it be better if the middleware was returning an error through the callback instead of throwing one directly ?

**Comment by KirillSuhodolov** [comment]
+1 for that

**Comment by godspeedelbow** [comment]
fixed (but not yet in NPM)

**Comment by godspeedelbow** [comment]
oops, wrong issue, my apologies

**Comment by godspeedelbow** [comment]
fixed in 1.0.0 (breaking change)
