### ISSUE TITLE
OAuth 2.0

### ISSUE THREAD

**Issue by rickihastings** [larafale/mangopay#60]
Any plans to implement this authentication method?

Thanks

**Comment by larafale** [comment]
not really, feel free to take a shot at it :)

**Comment by masterofdaemon** [comment]
is this why i get : ```
err { [MangoPayError: [object Object]]
  name: 'MangoPayError',
  message: 
   { Message: 'Your authorization do not allow you to access to this information',
     Type: 'not_authorized',
     Id: '43ce5044-1ffe-4e3c-a1a7-8bf6e68ac0db#1460056536',
     Date: 1460056537,
     errors: null } }
user { Message: 'Your authorization do not allow you to access to this information',
  Type: 'not_authorized',
  Id: '43ce5044-1ffe-4e3c-a1a7-8bf6e68ac0db#1460056536',
  Date: 1460056537,
  errors: null }
```

**Comment by godspeedelbow** [comment]
@masterofdaemon why do you think that it is related? Please provide more info on what method you're trying to use

**Comment by masterofdaemon** [comment]
fixed sorry
