### ISSUE TITLE
publish 1.0.0

### ISSUE THREAD

**Issue by godspeedelbow** [larafale/mangopay#67]
Hey @larafale,

I fixed some bugs, merged some PRs. Maybe you can add me as a contributor to the npm module (@godspeedelbow), I'll push out 1.0.0.

Reason I bumped major version is because one of the bug fixes is a breaking change.

Cheers!

**Comment by larafale** [comment]
just added you, make sure package json version is 1.0.0 and hit npm publish :)

**Comment by godspeedelbow** [comment]
sweet, thanks!

btw. any preferences on also publishing 0.x updates? I'd say, for now just
push forward and just have people upgrade. If we get questions about fixes
bugs in 0.x we can always consider then.

**Comment by godspeedelbow** [comment]
published
