### ISSUE TITLE
angular2 integration

### ISSUE THREAD

**Issue by mmazloum** [larafale/mangopay#76]
how would you load this in an angular2 project ? I can figure out how to import the module.

**Comment by godspeedelbow** [comment]
You would most likely not use this on the client side because in order to
use it you need to expose your private mangopay api keys in the browser.
This is a nodejs module

**Comment by mmazloum** [comment]
ok #fail question ;-) thanks
Do you now if there is any client-side angular2 friendly package ? I contacted them directly and didn't have positive feedback angular2 official integration wasn't on their Roadmap.

**Comment by godspeedelbow** [comment]
NP!

I think there's too much sensitive info involved to make it completely
client side. Just pop up a node js server :)

**Comment by mmazloum** [comment]
Good idea - but I'm inside a ionic2 project... and this means I would have to open a webview which is UX friendly. However thanks a lot for the job ;-)
