### ISSUE TITLE
violation of mangopay rules

### ISSUE THREAD

**Issue by fix** [larafale/mangopay#78]
Bonjour,

Nous avons constaté que vous utilisez une librairie non-officielle présentant une faille majeur de sécurité : https://github.com/larafale/mangopay

En utilisant cette librairie, vos clients valident le formulaire dans lequel ils saisissent leurs données sensibles de cartes sur votre site; celles-ci passent par votre serveur pour être ensuite envoyées sur le serveur PSP (côté Mangopay). Cela représente une grave faille règlementaire et une violation des règles PCI DSS. Il faut obligatoirement que les données de cartes soient envoyées directement sur le serveur PSP.

Vous devez impérativement vous mettre en conformité avant <snip> en utilisant la librairie officielle MANGOPAY : https://github.com/Mangopay/mangopay2-nodejs-sdk.

Au delà de ce délai, nous devront couper votre accès à l'API MANGOPAY le temps que vous publiiez un correctif.

Merci,
Cordialement,

Florian GUERRIER
EQUIPE MANGOPAY

**Comment by fix** [comment]
this function should not be used on server, but from client:

https://github.com/larafale/mangopay/blob/master/resources/card.js#L28

**Comment by Yhnlvy** [comment]
How about we work on a patch to fix this security breach up there ? I will give a try in the days ahead. 
Replacing a Node.js lib in such a critical workflow within two business days is completely insane !

**Comment by fix** [comment]
en fait il faut juste ne pas utiliser la méthode mentionnée et le faire au niveau du navigateur en javascript....

**Comment by fix** [comment]
I have just successfully tested card registration using https://github.com/Mangopay/cardregistration-js-kit

I guess the api should be removed and documented on README

**Comment by fix** [comment]
For info those interested, i have changed my client code this way (coffeescript)
Before (security issue):
```coffeescript
     payload =
        Currency: ...
        UserId: ...
        cardNumber: ...
        cardExpirationDate: ...
        cardCvx: ...
     
      # Connecting to backend server to perform all card registration process
      Meteor.call "Mangopay", "card.create", payload, (error,response) ->
        if error
          console.error error
        else
          console.log response
```

After (no security issue):
```coffeescript
    initdata =
       Currency: ...
       UserId: ...
   
    # connecting to server to get a token from mangopay (no security issue)
    Meteor.call "Mangopay", "card.initRegistration", initdata, (error, response) ->
        if error
          console.error error
        else
          payload = 
            cardNumber: ...
            cardExpirationDate: ...
            cardCvx: ...
          
          # mangoPay -> https://github.com/Mangopay/cardregistration-js-kit
          mangoPay.cardRegistration.init
            cardRegistrationURL: response.CardRegistrationURL
            preregistrationData: response.PreregistrationData
            accessKey: response.AccessKey
            Id: response.Id
        
          # connecting directly to PSP and Mongopay API
          mangoPay.cardRegistration.registerCard payload,
            (res) ->
              console.log res
            (err) ->
              console.error err
```

**Comment by larafale** [comment]
see #82
